"""30.10-ТМ

Revision ID: 0a78f65bad08
Revises: afc3bdbb28a1
Create Date: 2023-10-30 19:26:56.409540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a78f65bad08'
down_revision = 'afc3bdbb28a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('members_roles', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('members_roles')

    # ### end Alembic commands ###
