"""30.10-ТМ

Revision ID: afc3bdbb28a1
Revises: ce2c65842e3c
Create Date: 2023-10-30 17:35:47.366720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afc3bdbb28a1'
down_revision = 'ce2c65842e3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
